package com.aprovaenem.exam.domain.model;

import java.io.Serializable;

/**
 * Encapsulates the output of a Socratic AI consultation, explicitly indicating
 * whether the response was generated by the live LLM (Gemini) or served via
 * the resilient static INEP pedagogical fallback.
 */
public record TutorAiResult(
        String responseText,
        boolean isFallback
) implements Serializable {

    public static TutorAiResult success(String text) {
        return new TutorAiResult(text, false);
    }

    public static TutorAiResult fallback(String text) {
        return new TutorAiResult(text, true);
    }
}
